language: java
before_install:
- chmod +x gradlew
install:
- "./gradlew setupCIWorkspace"
script:
- "./gradlew clean build"
jdk:
- oraclejdk8
before_cache:
- find $HOME/.gradle/ -name '*.lock' -print -exec rm -f {} \;
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
sudo: false
before_deploy:
- export RELEASE_FILE_LIST=$(ls ./build/libs/* | tr '\n' ', ')
- echo "deploying $RELEASE_FILE_LIST to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "{$RELEASE_FILE_LIST}"
  on:
    repo: GlassPane/GlassPane
    tags: true
